### ISSUE TITLE
Attribute error in Significant-base-frequencies.py

### ISSUE THREAD

**Issue by TaliVeith** [acorg/mid#1]
`significant-base-frequencies.py --samFile 190802_15-against-Adeno.sam > out`

Error message:

Traceback (most recent call last):
  File "/home/tali/Darkmatter/env/bin/significant-base-frequencies.py", line 63, in <module>
    significantOffsets) = parseCommandLineOptions(args)
  File "/home/tali/Darkmatter/env/lib/python3.6/site-packages/midtools/options.py", line 61, in parseCommandLineOptions
    paddedSAM = PaddedSAM(args.samFile)
  File "/home/tali/Darkmatter/env/lib/python3.6/site-packages/dark/sam.py", line 428, in __init__
    referenceLengths = samFilter.referenceLengths()
AttributeError: 'str' object has no attribute 'referenceLengths'

**Comment by terrycojones** [comment]
You need to run `pip install -U dark-matter`.  If you first run the command `dark-matter-version.py` you'll see what version you have installed. Latest is 3.0.78.

**Comment by terrycojones** [comment]
This was fixed but not pushed to PyPI. Closing.
